version: '3'
services:
  app:
    container_name: search_ia
    image: node:21
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    working_dir: /app
    command: bash -c 'npm install && npm run build && npm run serve'
    ports:
      - '${PORT_SERVER}:${PORT_SERVER}'
