version: "3"

services:
  app:
    container_name: search_ia
    image: node:21
    restart: always
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    working_dir: /app
    command: bash -c 'npm install && npm run build && npm run serve'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.search-ia.rule=Host(`search-ai.ypw.com.do`)"
      - "traefik.http.routers.search-ia.entrypoints=websecure"
      - "traefik.http.routers.search-ia.tls.certresolver=le"
      - "traefik.http.services.search-ia.loadbalancer.server.port=${PORT_SERVER}"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
